### ISSUE TITLE
[Tracking issue] patches from IA's morituri fork to rebase to whipper

### ISSUE THREAD

**Issue by MerlijnWajer** [JoeLametta/whipper#35]
This is a tracking issue (for me) to contribute back the following changes that I made to our/my private fork of morituri. Context: I use morituri as-a-library (kind of), so we never invoke the main ripping code. This led me to having to shuffle a lot of code around, so in the end I'll also want to see if we can make whipper available as a library in a nice way. That involves removing various calls to exit(), for example.

* ARv2 support (using a faster tool): https://github.com/JoeLametta/whipper/issues/18
* ARv2 support in the report/log files: https://github.com/JoeLametta/whipper/issues/18
* [WIP] Data track support
* Logging improvements (remove flog)
* cdparanoia error parsing
* Ripping tracks only one, based on availability in AccurateRip
* Ripping tracks in fast mode, based on availability in AccurateRip
* Remove gstreamer dependencies by using 'flac' for encoding (the tool)
* shardz had a tool for peak detection, IIRC

Some of these features you may not want to merge even if rebased, because they may conflict with morituri's original goals (rip perfect, always twice, etc).

I will add expected dates (for PRs) soon, and update the issue accordingly.

**Comment by MerlijnWajer** [comment]
Somewhat far off, but possible after most of this is contributed, is(for someone)  to make a Qt frontend.

**Comment by JoeLametta** [comment]
> shardz had a tool for peak detection, IIRC

Merged (#48).
GStreamer peak detection is still there.

**Comment by RecursiveForest** [comment]
Correct, I didn't bother removing the gstreamer peak code so that merging a -gst patch would have fewer conflicts.

**Comment by JoeLametta** [comment]
Updated task list:

- [x] ARv2 support (using a faster tool): https://github.com/JoeLametta/whipper/issues/18 (See PR https://github.com/JoeLametta/whipper/pull/37)
- [x] ARv2 support in the report/log files: https://github.com/JoeLametta/whipper/issues/18
- [x] Logging improvements (remove flog)
- [x] Remove gstreamer dependencies by using 'flac' for encoding (the tool)
- [x] shardz had a tool for peak detection, IIRC
- [ ] [WIP] Data track support
- [ ] cdparanoia error parsing
- [ ] Ripping tracks only once, based on availability in AccurateRip
- [ ] Ripping tracks in fast mode, based on availability in AccurateRip
